### ISSUE TITLE
Add plugin slug to image path and URL filters

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/codepotent-update-manager#54]
# Description 
The image path/URL filters allow one plugin to override the header image of another; the alphabetically-last plugin using the filter takes precedence.

# Steps to Reproduce
Documented in [this issue](https://github.com/ClassicPress-plugins/classic-commerce/issues/257), filed with Classic Commerce, and also [discussed](https://forums.classicpress.net/t/possible-conflict-with-update-manager-images/2466) on the forum.

# Expected Behavior
Plugins cannot override header images.

# Additional Context
This is a bug, but, not considered critical at this time considering that the official ClassicPress Plugin Directory launch is imminent and the vast majority of 3rd party plugin updates will then be handled through the native update process. I'm creating this issue to ensure it is not lost in the mix and it will remain until an appropriate fix is implemented.

**Comment by nylen** [comment]
You probably already know this, but since this change requires plugin developers to make changes to their code, a semver major version bump is probably justified when these filters change.

**Comment by johnalarcon** [comment]
Yes, of course. 👍 Anytime the client file changed, it would be a major version bump.

**Comment by xxsimoxx** [comment]
As in many other filters is up to the caller function to check if they are changing their own things. 
Sure is misleading.
But if I add filters specific to the plugin but keep and deprecate misleading ones it requires just a minor version bump.
Am I right @nylen ?
