### ISSUE TITLE
Clicking "Install Update Now" button from Transients section does nothing

### ISSUE THREAD

**Issue by nylen** [xxsimoxx/codepotent-update-manager#65]
On a site with Update Manager (server) installed and at least one plugin update available, do the following:

1. Click "Update Manager > Transients" in the admin menu
2. Click the "Update Details" tab
3. Click "View Changes" on one of the available updates
4. Click the "Install Update Now" button at the bottom of the resulting dialog.

For me, nothing happens. There are no errors in the browser console and no network requests are triggered. This suggests that this button may not be wired up to anything but I have not looked in the code to check.

**Comment by xxsimoxx** [comment]
Good catch!

If the "View Changes" is opened in a new window it works.
Seems that the jQuery code triggering the update on button click depends on many information that are only on plugins page.
Same window for themes have no update button.

For now just hiding the button with b583e2b...
