### ISSUE TITLE
Error viewing plugin details

### ISSUE THREAD

**Issue by azurecurve** [xxsimoxx/codepotent-update-manager#72]
I have an issue with plugins which have been updated to the latest version of the Update Manager plugin.

When you click the PLugin Details link for a plugin the following error is displayed:
![image](https://user-images.githubusercontent.com/46169890/188493119-cfcf9c39-dc4b-4a7f-955f-23e8a53ecada.png)

**Comment by xxsimoxx** [comment]
Confirm that I also get `403` error on your plugins.
Changing the `UPDATE_SERVER` to mine (I've set up an endpoint for SMTP to test) everything works fine.

Can you try to change the content of your endpoint to something very basic to see if it happens too?

**Comment by azurecurve** [comment]
I set it to a template and filled in the key fields at the top and got the same result.

I only get this with the latest version; plugins using the older version are still working fine.

**Comment by xxsimoxx** [comment]
Still can't reproduce.
Is Update Manager at the latest version?
Can you turn on `WP_DEBUG` and see if there are some server-side logs?

**Comment by xxsimoxx** [comment]
Seems the issue is in how custom image filters are called in your new plugin structure.
This [PR](https://github.com/azurecurve/azrcrv-smtp/pull/9) solves the problem on your SMTP plugin.
I'll leave this issue opened for your feedback.

**Comment by azurecurve** [comment]
Hi Simone,
I can confirm your patch fixes the issue.
I'll try to bear this in mind in future if I encounter issues so I can do additional testing myself before logging an issue.
